# Generated by Django 3.0 on 2020-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumini', models.CharField(max_length=200)),
                ('company', models.CharField(choices=[('Google', 'Google'), ('Ashok Leyland', 'Ashok Leyland'), ('Accenger', 'Accenger'), ('Caterpiller', 'Caterpillar')], max_length=200)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
    ]
